### ISSUE TITLE
Add some security options for the GUI to provide separation of duties and address insecure login

### ISSUE THREAD

**Issue by dhixon** [phax/phoss-smp#102]
From a security perspective, provide a clean separation of duties between the public SMP API and the GUI by running them on different ports (or at least the option of running them on different ports).  The public SMP API webapp/port should only serve GET requests for the SMP API.  No writeable API's and no way to login to the GUI.     

I know that there are ways to use redirects for /secure to another URL that could be configured for HTTPS (though not the login page that runs in /public), but from a security perspective, I would prefer as much separation as possible between the external facing read-only elements and the internal facing read-write elements.

**Comment by phax** [comment]
New configuration option `webapp.public.login.enabled` in v5.2.0 to turn it off
