### ISSUE TITLE
Service Group Registration

### ISSUE THREAD

**Issue by skizub** [phax/phoss-smp#109]
We have a test SMP setup now (5.1.1 XML backend) connecting to SMK. PEPPOL Directory support is enabled. No issues in Tasks/Problems except notification about "test version" and missing service groups. SMP is was successfully registered with SMK.

**However when trying to register Service Group - getting a following error in logs:**
JAXP: find factoryId =javax.xml.stream.XMLOutputFactory
---[HTTP request - https://acc.edelivery.tech.ec.europa.eu/edelivery-sml/manageparticipantidentifier]---
Accept: text/xml, multipart/related
Content-Type: text/xml; charset=utf-8
SOAPAction: "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :createIn"
User-Agent: JAX-WS RI 2.2.10 svn-revision#919b322c92f13ad085a933e8dd6dd35d4947364b
<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><CreateParticipantIdentifier xmlns="http://busdox.org/serviceMetadata/locator/1.0/" xmlns:ns2="http://busdox.org/transport/identifiers/1.0/"><ServiceMetadataPublisherID>TEST-SMP-TRANS</ServiceMetadataPublisherID><ns2:ParticipantIdentifier scheme="iso6523-actorid-upis">9915:test2</ns2:ParticipantIdentifier></CreateParticipantIdentifier></S:Body></S:Envelope>--------------------

[2019-07-02T16:12:22,486] [SMP-SERVER] [INFO ] [http-nio-80-exec-4] Response exception processed in Tube [ com.sun.xml.ws.transport.DeferredTransportPipe ] Instance [ 2 ] Engine [ JAX-WS RI 2.2.10 svn-revision#919b322c92f13ad085a933e8dd6dd35d4947364b: Stub for unknown ] Thread [ http-nio-80-exec-4 ]:
com.sun.xml.ws.client.ClientTransportException: HTTP transport error: java.lang.NullPointerException
	at com.sun.xml.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:131)
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:218)
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:145)
	at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:139)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
	at com.sun.xml.ws.client.Stub.process(Stub.java:463)
.....

Any ideas what may cause that exception? Looks like SMP is not receiving what it is expecting from SMK....?

**Comment by phax** [comment]
@skizub  Can you please post the URL of your SMP here, than I can cross check the settings if you don't mind. Thx

**Comment by skizub** [comment]
[smp.transalis.com](url)

**Comment by phax** [comment]
Thanks - got it. Configuration looks good. The only thing I stumbled upon was an invalid PEPPOL Directory URL. Please remove the "/public" there.

So I have no real idea what causes this error, so let me phrase a couple of questions:
* Are you using a Docker image, or did you deploy the WAR or did you build it yourself?
* Do you have an HTTP/HTTPS proxy server in place?
* Are you using a central TLS termination like BlueCoat or so?
* Did you change anything on the specification after your got this error?

Thanks

**Comment by skizub** [comment]
@phax - thank you.
I removed "/public" from PEPPOL directory but it didn't changed anything in terms Service registration error.
_Are you using a Docker image, or did you deploy the WAR or did you build it yourself?_
We are using WAR from GitLab, but have an option to rebilud whole project in latest IntelliJ

_Do you have an HTTP/HTTPS proxy server in place?_
Yes it was enabled in configuration. When I commented it out and restarted application started to receive a different - SSL handshake - exception. Should we have SSL enabled in test?

**Comment by phax** [comment]
@skizub  Thanks for the quick response. Stick with the WAR - all good. Okay, so we have a proxy server - that helps in moving forward.

The configuration items for the proxy need documentation - my mistake. Here they are, for `smp-server.properties´ (available since v5.0.7):
* **http.proxyHost**: Proxy host name or IP address for HTTP connections
* **http.proxyPort**: Port number of the proxy host to use for HTTP connections
* **https.proxyHost**: Proxy host name or IP address for HTTPS connections
* **https.proxyPort**: Port number of the proxy host to use for HTTPS connections
* **proxy.username**: Optional user name for the proxy server.
* **proxy.password**: Optional password for the user on the proxy server

You may need to add the "https" stuff as well???

**Comment by skizub** [comment]
@phax Many thanks for updating documentation on proxy details.

I'll try to implement https and update ticket with results a bit later.

**Comment by phax** [comment]
And also see https://github.com/phax/phoss-directory/#pd-client for the HTTP Proxy configuration in the PEPPOL Directory client

**Comment by skizub** [comment]
Philip, SSL handshake problem was resolved using https://github.com/phax/phoss-smp/issues/96. Also I was able to use keystore uploaded by you previously:  https://github.com/phax/peppol-commons/blob/master/peppol-commons/src/main/resources/truststore/complete-truststore.jks

We are good now - **many thanks for your help**. Feel free to close this ticket.

**Comment by phax** [comment]
@skizub Thanks for the update and enjoy the SMP :)
Have a great weekend
