### ISSUE TITLE
Unable to find Service group on peppol.helger.com

### ISSUE THREAD

**Issue by vinoddanekar** [phax/phoss-smp#113]
Hello Philip,

I am not able to see our service groups on Helger website:
https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?action=perform&scheme=iso6523-actorid-upis&value=0106%3A27152051&sml=digitprod

Our SMP: https://peppol.bluzor.com/public/
Sample Participant to Test: 0106:27152051

Recently, we changed IP -
Current IP: 84.241.153.27 (old IP: 84.241.175.134)

As per guidelines, we deleted existing SML registration and registered again using:
https://peppol.helger.com/public/locale-en_US/menuitem-tools-smp-sml (currently, present within SMP portal)
Also, we deleted and created service groups again.
In SMP portal there is no error I see in tasks and problem section. Also all SMP queries show success results.

Can you please guide me on this?
Vinod

**Comment by phax** [comment]
Hi Vinod.
so I can confirm your SMP registration is correct.
The problem seems to be a configuration on your side.
When you e.g. try to open http://B-ad59c71cfeb7d3ac17a28bfd660b2a71.iso6523-actorid-upis.edelivery.tech.ec.europa.eu in your browser, you get an empty page.
Your SMP needs to be reachable by different hostnames, and that is something where you need to take special care of. See the Wiki page at https://github.com/phax/phoss-smp/wiki/Running#running-behind-an-httpd for configuration examples of common reverse proxies.
And btw. you may consider upgrading your SMP to a later version....
hth, Philip

**Comment by vinoddanekar** [comment]
Hi Philip,
Thanks for quick reply. According to configuration smp.forceroot is already set to true. I am not using proxy, tomcat is working on Windows on 80 port only.

Confusing thing is that, it was working already. I could see my service groups on Helger.com tools but when I changed IP then they stopped appearing on Helger.com tools. After changing IP I deleted SML registration and registered with new IP again. Also, I deleted and recreated service groups too. I did have any change in configuration, etc.

Can you please tell me any common mistake in such scenario? If more details on configuration are needed then I can provide.

**Comment by phax** [comment]
I have no experience with running it in plain Tomcat only.
I woulld suggest you try the following:
Open http://B-ad59c71cfeb7d3ac17a28bfd660b2a71.iso6523-actorid-upis.edelivery.tech.ec.europa.eu  in a browser and check your access logs. Check if you have incoming connections at all - ask your network experts.... Maybe it's a simple firewall issue

**Comment by vinoddanekar** [comment]
Hi Philip,
Thanks for support.
We had `http` to `https` auto redirection enabled recently. I disabled it and then added alias for peppol name url to smp host only. Now, its working.

Can you please mention in your documentation explicitly that do not use https redirection because its a common practice to auto-redirect http traffic to https?

Seems like, peppol name url should be alias for smp host, then only it works.

Closing issue.

**Comment by vinoddanekar** [comment]
Hi Philip,

Everything was working fine since last update.
Today, I upgraded from version 5.0.0 to 5.2.0 with 3 simple steps:
1. Download phoss-smp-webapp-sql-5.2.0.war
2. Mount it in TomCat
3. Replace .properties files with old so that existing settings remain same.

SMP https://peppol.bluzor.com/public shows everything correct and working..
But, following two issues:
When I tried to create service group it showed error:

> Error creating the new SMP ServiceGroup for participant 'iso6523-actorid-upis::27152051'.
> Technical details: SMPSMLException - Failed to create 'iso6523-actorid-upis::27152051' in SML
> Caused by: RegistrationHookException - Could not create business iso6523-actorid-upis::27152051 in SML
> Caused by: ClientTransportException - The server sent HTTP status code 400: Bad Request
> 
Note: I deleted above participant first and then tried to create it again.
SMP name: http://PEPPOL-BLUZOR-SMP.publisher.edelivery.tech.ec.europa.eu is accessible.

Can you please let me know the possible issue?

**Comment by phax** [comment]
I am on vacation. Will check next week. See the Wiki which has a page on SML error codes

**Comment by vinoddanekar** [comment]
Thanks for Reply Philip.
I see today, I am able to create a deleted Participant using GUI. May be after deleting participant, SML needed some additional time to reflect it. Bit strange but today Delete and create worked flawlessly multiple times.

Somehow, I am still not able to create participant through PUT API whereas other APIs work e.g. Delete participant.

**Comment by phax** [comment]
@vinoddanekar yes it may happen, that there is a certain delay in these operations, because the DNS changes may take some time until they are replicated. Its up to 24 hours until everything is replicated, and than there is your local DNS client cache, and the OS DNS client cache, and the Java DNS client cache... it's basically impossible to get a consistent, reproducable DNS queries 🤷‍♂ 

See https://zwischenzugs.com/2018/06/08/anatomy-of-a-linux-dns-lookup-part-i/ and https://zwischenzugs.com/2018/06/18/anatomy-of-a-linux-dns-lookup-part-ii/ for amazing details on that topic

**Comment by vinoddanekar** [comment]
@phax 
Thanks for info on DNS reflection.

> Somehow, I am still not able to create participant through PUT API whereas other APIs work e.g. Delete participant.

Is there any known issue for create service group API? Others working good but Create service group throw error 500. Before migration it was working correct. No changes in environment, other than version upgrade, are done.

**Comment by phax** [comment]
Sorry I missed that one.
The XSD checks for the incoming structure were added, so please ensure that your create request has the necessary elements.

I am not at my machine but if I remember correctly some I between empty element is necessary

**Comment by ri4a** [comment]
Try adding an empty

```
<ServiceMetadataReferenceCollection/>
```

element in the

```
<ServiceGroup/>
```

**Comment by vinoddanekar** [comment]
@phax @ri4a 
Thank you for helping me out.
I had few more namespaces referred in old request removed them all and added `<ServiceMetadataReferenceCollection/>`
Started working.
Thanks :)

For others, you can refer request xml schema here:
http://docs.oasis-open.org/bdxr/bdx-smp/v1.0/csprd01/bdx-smp-v1.0-csprd01.html#_Toc396121907

**Comment by phax** [comment]
And when using the Peppol API, see the following Schema:
https://github.com/phax/peppol-commons/blob/master/peppol-commons/src/main/resources/schemas/ServiceMetadataPublishingTypes-1.0.xsd
