### ISSUE TITLE
Broken link to new release of SMP server

### ISSUE THREAD

**Issue by JonasZal** [phax/phoss-smp#115]
Link (added below) to the new version of SMP server is not found. Can you fix it in README.md

https://github.com/phax/phoss-smp/releases/tag/peppol-smp-server-parent-pom-5.2.0

**Comment by phax** [comment]
Thanks for pointing that out. The correct link is https://github.com/phax/phoss-smp/releases/tag/phoss-smp-parent-pom-5.2.0
