### ISSUE TITLE
Task/problems page does not show expired certificates

### ISSUE THREAD

**Issue by RovoMe** [phax/phoss-smp#120]
Expired certificates, such as the one listed below, do not show up in the respective `Tasks/problems` page in the SMP while the certificate page hints about the certificate being no longer valid.

![expiredCertificate](https://user-images.githubusercontent.com/1712331/72535919-a0e85380-3879-11ea-84a6-cda5a8ca9a5c.png)

**Comment by phax** [comment]
Fixed in v5.2.1 release - thx for the input 👍
