### ISSUE TITLE
Unable to create End point using API

### ISSUE THREAD

**Issue by vinoddanekar** [phax/phoss-smp#121]
Hi,

I am using APIs to create service groups and End points. After upgrade to 5.2, with some tweaks I am able to create service groups. But when I try to create End points, I get Error 500. Following is my XML request (sensitive data removed)-

```html
PUT https://sitename.com/iso6523-actorid-upis::0106:{KvK}/services/busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:extended:urn:www.peppol.eu:bis:peppol4a:ver1.0::2.0
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<SignedServiceMetadata
  xmlns="http://docs.oasis-open.org/bdxr/ns/SMP/2016/05"
  xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ServiceMetadata>
    <ServiceInformation>
      <ParticipantIdentifier scheme="iso6523-actorid-upis">0106:{KvK}</ParticipantIdentifier>
      <DocumentIdentifier scheme="busdox-docid-qns">urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:extended:urn:www.peppol.eu:bis:peppol4a:ver1.0::2.0</DocumentIdentifier>
      <ProcessList>
        <Process>
          <ProcessIdentifier scheme="cenbii-procid-ubl">urn:www.cenbii.eu:profile:bii04:ver1.0</ProcessIdentifier>
          <ServiceEndpointList>
            <Endpoint transportProfile="busdox-transport-as2-ver1p0">
              <EndpointURI>https://sitename.com/oxalis/as2</EndpointURI>
              <RequireBusinessLevelSignature>true</RequireBusinessLevelSignature>
                <ServiceActivationDate>
                  2019-01-16T01:00:00.000+01:00
                </ServiceActivationDate>
                <ServiceExpirationDate>
                  2026-03-15T01:00:00.000+01:00
                </ServiceExpirationDate>
              <Certificate>{Certificate}</Certificate>
              <ServiceDescription>test</ServiceDescription>
              <TechnicalContactUrl>https://sitename.com</TechnicalContactUrl>
              <TechnicalInformationUrl>https://sitename.com</TechnicalInformationUrl>
            </Endpoint>
          </ServiceEndpointList>
        </Process>
      </ProcessList>
    </ServiceInformation>
  </ServiceMetadata>
  <ds:Signature/>
</SignedServiceMetadata>
```
Can you please let me know if I am missing something?

References:
https://github.com/phax/phoss-smp/blob/master/docs/CEF%20Conformance%20Testing/SignedServiceMetadata-template.xml
http://docs.oasis-open.org/bdxr/bdx-smp/v1.0/os/bdx-smp-v1.0-os.html#_Toc490131069

**Comment by phax** [comment]
Hi @vinoddanekar 
The PUT API requires a `ServiceMetadata` element only and no `SignedServiceMetadata`.
The example above would be okay, if you are using an SMP that follows the OASIS BDXR specification.
But if you instead want to use that for Peppol, the structure is not valid - see https://github.com/phax/peppol-commons/blob/master/peppol-commons/src/test/java/com/helger/peppol/smp/marshal/SMPMarshallerServiceMetadataTypeTest.java this as an example instead.
hth

**Comment by vinoddanekar** [comment]
Thank you so much. Working now.
@phax Can you please remove test (https://github.com/phax/peppol-commons/blob/master/peppol-commons/src/test/java/com/helger/peppol/smp/marshal/SMPMarshallerServiceMetadataTypeTest.java)
Or SMP address from it?

**Comment by phax** [comment]
Thanks for confimation.
Server names were changed
