### ISSUE TITLE
Enabling Peppol Directory

### ISSUE THREAD

**Issue by ri4a** [phax/phoss-smp#122]
Hi Philip,

When adding

```
smp.peppol.directory.integration.enabled = true
smp.peppol.directory.hostname = https://test-directory.peppol.eu
```

in smp-server.properties, I expected these settings to become active upon restart of Tomcat. However, I had to change the settings in the UI to get them to work.

What am I missing?

Thanks!

**Comment by phax** [comment]
Hi @ri4a ,
yes the settings have precedence in this case 🤷‍♂ 
I guess in this case we need a writable REST API to set the settings....??
Any ideas?
Thanks,
  Philip

**Comment by ri4a** [comment]
Hmmm...I would like the config files to take precedence. That way I can provision a new SMP server using a script (e.g. capistrano).

Perhaps a new setting

```
global.config.precedence=file
```

which would keep current behaviour if not present?

Because of #97 it we can no longer use the UI in production, so that will be a challenge.

Are the settings from the UI stored in

```
webapp.datapath
```

? In that case, could I simply edit these files instead of using the UI?

**Comment by phax** [comment]
Yes, inside the data path there is a file `smp-settings.xml` which contains the settings. It should be pretty straight forward to change the value there.

Concerning #97 - I am aware of it, but this is indeed quite some effort and currently there are so many other things...

**Comment by ri4a** [comment]
Ok, we will make changes directly in smp-settings.xml. Thanks!
