### ISSUE TITLE
Redirects to http://localhost:18080/secure

### ISSUE THREAD

**Issue by AlexandruCiobanu** [phax/phoss-smp#126]
I am running the smp with Tomcat (running on port 18080) and I get redirects to http://localhost:18080/secure even though that should be the actual domain of the machine the server is on. Any idea what can i do to solve it?

**Comment by phax** [comment]
Hi, this is most likely related to the property `smp.publicurl` in `smp-server.properties` being not set or set to the default. It's usually hard for applications to determine the outside domain name, so you need to configure it manually. See https://github.com/phax/phoss-smp/wiki/Configuration#smp-serverproperties for further configuration items.

**Comment by AlexandruCiobanu** [comment]
I do have that variable setup. When I post  /secure I get redirected to that localhost. Can I see in debug if that variable was picked up correctly? i don't know what else to do

**Comment by phax** [comment]
Are you using the latest version 5.2.3 or what version are you using? Why would you `POST` to `/secure`? 
`/secure` is "just" the UI for the Admin GUI and needs `GET`

**Comment by AlexandruCiobanu** [comment]
latest version. Sorry, I meant I go to the secure page then login from there. That redirects me to localhost

**Comment by phax** [comment]
Okay, well that's what it is supposed to do. Do you eventually have a reverse proxy configured that does not pass the Cookies or some HTML hidden parameters through?
Shall we have a short skype call where you can share screen? Or can you elaborate more detailed on your system architecture by email (philip at helger dot com)?

**Comment by AlexandruCiobanu** [comment]
your reply gave me the idea of checking the location header rewrite in the reverse proxy and that was the issue. I was using nginx and did not handle the redirect header in the proxy pass. Thanks!

**Comment by AlexandruCiobanu** [comment]
I may have spoken too soon. It redirects correctly now but it still presents me with the secure login page. I saw that if I enter a wrong pwd I get an error notification. am I missing anything?

**Comment by AlexandruCiobanu** [comment]
Seems to be a cookie issue: JSESSIONID=B829F11E52925E15ED4ABDBEA7DBB376; Path=/phoss-smp-webapp-sql-5.2.3; HttpOnly. hmmm, checking to see how to fix that path

**Comment by AlexandruCiobanu** [comment]
```
proxy_redirect http://localhost:18080/ /;
proxy_cookie_path ~([a-z0-9\.\/\-]+)$ /;
```

This solved my issues. It seems that the `smp.publicurl` value is not taken into account for some reason

**Comment by phax** [comment]
Yes, the cookie comes from the Application server and I don't have influence on it.... :(

**Comment by phax** [comment]
Is there anything you can add to https://github.com/phax/phoss-smp/wiki/Running#running-behind-an-nginx ?

**Comment by AlexandruCiobanu** [comment]
yes, `proxy_cookie_path ~([a-z0-9\.\/\-]+)$ /;` because the cookie's path is the actual war root and it needs to go cos it will likely not be like that for the outside

**Comment by phax** [comment]
Okay thanks. As this was already contained as `proxy_cookie_path /smp /;` (assuming the context `/smp`) I think it does the trick. The deployment context is so subjective....
