### ISSUE TITLE
SML Registration Problem

### ISSUE THREAD

**Issue by ladyjer** [phax/phoss-smp#127]
Hi,

I'm trying to register my test PHOSS server on SMK. I get this Java error:

`Error registering SMP 'SBI-SMP-ID1' with physical address '***' and logical address '****' to the SML 'https://acc.edelivery.tech.ec.europa.eu/edelivery-sml'.
Technical details: ClientTransportException - HTTP transport error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: SSLHandshakeException - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: ValidatorException - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: SunCertPathBuilderException - unable to find valid certification path to requested target`

I have a great doubt abount sml.smpid in smp-server.properties. In PHOSS Documentation I can read:

`sml.smpid: The SMP ID to use when using the SML interface.
Note: it must be the same ID that was used for the initial registration of the SMP to the SML.
Note: is only required if the entry sml.active is set to true.`

I have to register the ID 'SBI-SMP-ID1' somewhere else before trying to register PHOSS from within  'Administration -> SML -> SML Registration'?

Thanks in advance

**Comment by phax** [comment]
Hi Mariella,
most likely you run into the problem, that the TLS certificate of the SMK was updated by end of last year.
What SMP version are you using?
According to my information the SMP ID "SBI-SMP-ID1" is free to be used on SMK.
hth,Philip

**Comment by ladyjer** [comment]
Hi,

I'm using phoss SMP [Test version] 5.2.0 with PEPPOL API

**Comment by phax** [comment]
Please update to 5.2.2 or higher for the updated trust store:
https://github.com/phax/phoss-smp/wiki/News-and-noteworthy

**Comment by ladyjer** [comment]
Thank you!

**Comment by phax** [comment]
Did it solve it your problem? If so, please close the issue

**Comment by ladyjer** [comment]
I'm going to migrate tomorrow or Thursday at the latest. I keep you updated. If it'll fix the issue, I will close the issue for sure.

**Comment by ladyjer** [comment]
Hi, 
I've installed version 5.2.3. Now the error is different:

`Error registering SMP 'SBI-SMP-ID1' with physical address '217.19.151.239' and logical address 'http://sbiphts01.sbitalia.com' to the SML 'https://acc.edelivery.tech.ec.europa.eu/edelivery-sml'.
Technical details: ClientTransportException - The server sent HTTP status code 401: Unauthorized`

**Comment by phax** [comment]
Okay, we're getting closer. My assumption is, that your certificate is invalid or expired.
Can you please check the "Certificate information" page to check whether it states that you are using a correct "Peppol pilot certificate"?
Alternatively ping me on Skype at phelger

**Comment by phax** [comment]
The issue was based on a wrong certificate (AP instead of SMP). Closed for now
