### ISSUE TITLE
HTTP status code 400: Bad Request when trying to register a new service group

### ISSUE THREAD

**Issue by primeXchange** [phax/phoss-smp#129]
Setting up a TEST and PROD SMP, TEST works fine.

When trying to register a new service group using a PROD cert with global.production = true and being registered in the SML, an error occurs.

[tomcat_log.txt](https://github.com/phax/phoss-smp/files/4592886/tomcat_log.txt)

What could be the problem?

using phoss-smp-webapp-xml-5.2.3
```
Error creating the new SMP ServiceGroup for participant 'iso6523-actorid-upis::9930:de316049661'.
Technical details: SMPSMLException - Failed to create 'iso6523-actorid-upis::9930:de316049661' in SML
Caused by: RegistrationHookException - Could not create business iso6523-actorid-upis::9930:de316049661 in SML
Caused by: ClientTransportException - The server sent HTTP status code 400: Bad Request
```

![smp1](https://user-images.githubusercontent.com/40356316/81293756-1f0d7780-906e-11ea-8714-4bb00a4b3dc9.png)
![smp2](https://user-images.githubusercontent.com/40356316/81293764-203ea480-906e-11ea-9868-a31a2b7dc279.png)
![smp3](https://user-images.githubusercontent.com/40356316/81293765-216fd180-906e-11ea-9ddd-e0c302479e9d.png)
![smp4](https://user-images.githubusercontent.com/40356316/81293768-216fd180-906e-11ea-97d7-2272fbf0ff3b.png)
![smp-error](https://user-images.githubusercontent.com/40356316/81293773-22086800-906e-11ea-9698-82513719d8b7.png)

**Comment by phax** [comment]
Problem was solved

**Comment by ic-officient** [comment]
> Problem was solved

Dear Philip,

could you describe what the was the cause of this problem and how it was resolved?
I just got the same problem.

Kind regards,
Ivan

**Comment by primeXchange** [comment]
Hello Ivan,

in our case it was an issue with an entry in the SML that was already set for some reason, that gave an error when our SMP tried to tell the SML to write the record again. The fix was:

- Login to your SMP
- Goto Administration|SMP Settings
- Uncheck the “SML enabled” checkox
- Create the Service group in your SMP
- Go back to the SMP Settings and re-enable the SML Connection

After that, the record registered fine and is working.

**Comment by phax** [comment]
Hi guys, please see #152  - i think more of you are affected.

**Comment by ic-officient** [comment]
Thanks, I have tried it and I was able to import the new service groups without errors, and I enabled the SML again. But the registrations are not visible.
I can't find them by searching in the service group menu of my SMP, but I can find them in the MYSQL database underneath.
I noticed that all the menus under "Endpoints" now give "Internal error".
Strange.

**Comment by divyanshu150** [comment]
hi @phax @primeXchange DETAILS:	Error: Could not Notify SML of participant details change: The server sent HTTP status code 400: Bad Request

hi @phax i am not able to add endpoint smp  can you please guide me
due to this its not adding service group content and business card

![Image](https://github.com/user-attachments/assets/04cf12df-50e8-4abf-b79d-5d1209a7434d)

please guide me also

**Comment by phax** [comment]
@divyanshu150 please create a separate issue for that and don't add to old ones - thank you
