### ISSUE TITLE
Identifier dependent SMP host

### ISSUE THREAD

**Issue by ri4a** [phax/phoss-smp#130]
Hi Philip,

We are interested in associating a unique SMP host with each identifier. The response would contain that host, e.g.

    http://<host>/iso6523-actorid-upis::0000:00000000/services/etc

Thanks!

**Comment by amaters-easy** [comment]
I think this is the issue we discussed last week over mail. Would be nice to see it in the next release

**Comment by phax** [comment]
@amaters-easy Nope that is something else. This issue is only about the reponse hostname for SMP responses and has nothing to do with lookups.

**Comment by ri4a** [comment]
We retract this feature request.
