### ISSUE TITLE
Anonymous SMP host

### ISSUE THREAD

**Issue by ri4a** [phax/phoss-smp#131]
Hi Philip,

We are interested in showing an anonymous SMP host. The response would then be something like

    http://b-<hash>..iso6523-actorid-upis.edelivery.tech.ec.europa.eu/iso6523-actorid-upis::0000:00000000/services/etc

Thanks!

**Comment by phax** [comment]
The possibility is now there - just need to make it customizable now

**Comment by phax** [comment]
In version 5.2.4 this can be enabled by setting
```
smp.publicurl.mode = dynamic-participant
```
in smp-server.properties
