### ISSUE TITLE
Error creating the new SMP ServiceGroup

### ISSUE THREAD

**Issue by skizub21** [phax/phoss-smp#154]
Hello,

In Phoss SMP server I'm trying to Create new Service group using Service Groups menu. 
When I enter identifier a value into Participant ID field, select user and click on Save I'm getting a following error:
![smp_error](https://user-images.githubusercontent.com/78475687/106749766-3c846780-6627-11eb-9200-4fe5a26ae165.png)

In server log there is a single line saying that:
[2021-02-03T12:53:12,860] [SMP-SERVER] [INFO ] [http-nio-80-exec-5] Performing SML query to 'https://edelivery.tech.ec.europa.eu/edelivery-sml/manageparticipantidentifier' -- com.helger.peppol.smpserver.smlhook.RegistrationHookWriteToSML._createSMLCaller(RegistrationHookWriteToSML.java:70)
[2021-02-03T12:53:12,861] [SMP-SERVER] [INFO ] [http-nio-80-exec-5] Trying to create new participant iso6523-actorid-upis::0088:5060089608714 in SMP 'PROD-SMP' -- com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.create(ManageParticipantIdentifierServiceCaller.java:159)

SMP configuration is ok according to the server:
![smp_configuration](https://user-images.githubusercontent.com/78475687/106750194-cdf3d980-6627-11eb-9b8f-8fe9db287ca0.png)

Any idea what could be wrong?

**Comment by phax** [comment]
Hi @skizub21,
Here are some questions:
* Have you initially registered your SMP to the SML? For test or production?
* Do you want to use it for Peppol or CEF/with OASIS BDXR spec?
* What is your SMP ID?
Best, Philuo

**Comment by skizub21** [comment]
Thanks Philip.
Answers to your questions:
I'm trying to add to production SMP, connecting to production SML: 'https://edelivery.tech.ec.europa.eu/edelivery-sml/manageparticipantidentifier'. Our SMP ID is PROD-SMP-TRANS. This is not the first Service Group I'm creating. First one was created at setup stage and is currently used in production.

**Comment by skizub21** [comment]
and ... we are adding Service Group for PEPPOL spec

**Comment by phax** [comment]
Did you eventually recently receive a new Peppol certificate and forgot to "update the certificate" at the SMP?
If that seems reasonable, read this: https://peppol.helger.com/public/locale-en_US/menuitem-docs-peppol-cert-update#smp

**Comment by skizub21** [comment]
Your are right - we updated our SMP, but forgot to notify SML. 

In order to fix this I was trying to do Certificate Update via SMP frontend, but without any luck:
![SMLCertUpdate](https://user-images.githubusercontent.com/78475687/106771319-1ec2fc80-663f-11eb-9607-db5a144ac1a4.png)

Any ideas what else could be wrong?
Also it says that our certificate is still valid and expires 4th of Jul, but this is not right - our certificate has expired approximately 2 months ago... Is there a way to check which certificate registered in SML will expire in a few months.

**Comment by phax** [comment]
See https://peppol.helger.com/public/locale-en_US/menuitem-docs-peppol-cert-update#smp - you need to write to CEF support with the details of the old and the new certificate.

**Comment by skizub21** [comment]
Understand.
Thank you very much for you help, Philip

**Comment by skizub21** [comment]
More on SMP update issue... I checked with CEF eDelivery team and they confirmed that SMP certificate we are currently using is valid. They advised it could be a network issue. 

When trying to connect to  https://edelivery.tech.ec.europa.eu/edelivery-sml/manageparticipantidentifier using WGET I'm getting SSL handshake error. Could it be SSL issue?

**Comment by phax** [comment]
Could be - what version are you using? Did you configure a custom truststore? See property `smp.truststore.path`

**Comment by skizub21** [comment]
Yes I have truststore and there is about 20 different certificates in it, some are not valid, some are test. Do you know what is the best way to identify which ones are required for SML update?

**Comment by skizub21** [comment]
We are using a version downloaded from https://github.com/phax/peppol-commons 2 years ago - filename complete-truststore.jks

**Comment by skizub21** [comment]
Just resolved the problem and created new Service Group.
Steps were following:
1. Identify truststore file location.
2. Get certificates from the server(in PEM format):
   openssl s_client -showcerts -connect edelivery.tech.ec.europa.eu:443 
3. Save them to files
4. Import PEMs to truststore:
keytool -import -alias <youralias> -keystore <yourJKSfile> -file <PEMcertifiate>

After reload of keystore on Phoss SMP - all started to work as expected.

**Comment by phax** [comment]
Or you just grab the new truststore from https://github.com/phax/peppol-commons/tree/master/peppol-commons/src/main/resources/truststore

The change was done in version 5.0.5 - see https://github.com/phax/phoss-smp/wiki/News-and-noteworthy

Thanks for your feedback @skizub21
