### ISSUE TITLE
Unable create business card, rest works fine.

### ISSUE THREAD

**Issue by vinoddanekar** [phax/phoss-smp#159]
Hi Philip, 
While creating business card I get error "Error creating the Business Card for Service Group 'iso6523-actorid-upis::0106:00000000'". I select participant, provide name and country which are mandatory.
00000000 - is masked value.

Also, I guess, due to this our service groups are not appearing peppol directory. Respective settings are in place as mentioned in image below -
![image](https://user-images.githubusercontent.com/46052955/111120822-dbd73b80-8591-11eb-841e-641115c58e50.png)

All other operations like managing service groups, end points are working fine.
Version: phoss SMP 5.2.0 with PEPPOL API. 
Backend: SQL

Can you please let me know what would be the issue? and how to solve it?

Thanks.

**Comment by phax** [comment]
Hi,
did you update from an old version of the SMP?
The error message indicates, that some went wrong when communicating with the database.
Please have a view at the logs.
Best, Philip

**Comment by vinoddanekar** [comment]
> Did you update from an old version of the SMP?
No. We are using this version since a year. But, yes recently we updated pki certificates. Earlier we did not use to create business cards but recently we see that our services groups dont appear in peppol directory. So, I felt it could be due to business card issue.

> Please have a view at the logs.
I will recheck but when I tried to create business card then error appeared on UI but no suspicious logs found.

**Comment by phax** [comment]
Okay, than I assume it has something to do with the truststore, because the Let's Encrypt CA of the Directory is expiring soon.
Please try replacing your existing truststore with the version provided at https://github.com/phax/peppol-commons/tree/master/peppol-commons/src/main/resources/truststore - it should have the latest and greatest certificates. This requires a restart of the SMP.

**Comment by vinoddanekar** [comment]
Sure. Thanks. I will do it and revert.

**Comment by vinoddanekar** [comment]
Hi,
I checked logs in detail, found that SQL had a problem. Fixed that table.
Now it creates Business card but does not update to PEPPOL directory. In logs, I found that its 'SSL handshake' error. I tried replacing above trust store i.e. https://github.com/phax/peppol-commons/blob/master/peppol-commons/src/main/resources/truststore/complete-truststore.jks but no luck. That too says expiring in 2 days.

Anything wrong with LetsEncrypt?
Its creating problem for Directory update. Rest all works fine.

**Comment by phax** [comment]
Did you update the path in both `smp-server.properties` AND `pd-client.properties`? You need to update the location it in both files

**Comment by vinoddanekar** [comment]
Yes. both places keystore and truststore are same.

**Comment by phax** [comment]
Yes, the new truststore contains the old certificate, but it should also contain the new one.
If you open the page "Certificate Details" and go to the tab "Peppol Directory TrustStore", do you see the R3 certificate "r3 (isrg root x1)" in it? If yes, then the truststore is good.

**Comment by vinoddanekar** [comment]
Yes. I see -
CN=R3,O=Let's Encrypt,C=US.

**Comment by phax** [comment]
Hm okay. Weird. Anything else related to your certificates under "Tasks/problems"?

**Comment by vinoddanekar** [comment]
Following is screenshot for our test environment:
![image](https://user-images.githubusercontent.com/46052955/111264376-66c93c00-864d-11eb-819a-b2cfcac2abe6.png)

For production:
Debug mode is False & Production mode is True

Public URL is not configured on both test and production.

Issue exists on Both - Prod & Test.

**Comment by phax** [comment]
Okay, that all looks good. These are minor issues, but nothing in relation to the Peppol Directory.
The public URL should be configured to produce consistent results.
Are you using a PKCS12 or JKS keystore? If PKCS12, please check that the name of the alias is case sensitive - so that the entry in the properties files is **exactly** as it is in the keystore itself, as e.g. `a` != `A`

**Comment by phax** [comment]
Can you please send me the public URL of your SMP (either here or by email), so that I can have a look? Thx

**Comment by vinoddanekar** [comment]
> If PKCS12, please check that the name of the alias is case sensitive - so that the entry in the properties files is **exactly** as it is in the keystore itself

Yes we have same alias is keystore. Case sensitivity is managed.

**Comment by vinoddanekar** [comment]
> Can you please send me the public URL of your SMP (either here or by email), so that I can have a look? Thx

Will forward on email.

**Comment by phax** [comment]
Okay, so the problem with your test server simple:
you need to change the Directory URL from `https://directory.peppol.eu"` tio `https://test-directory.peppol.eu"`.

**Comment by phax** [comment]
Another problem is the automatic forward from "http" to "https" - that is not allowed. The SMP MUST run on http, port 80

**Comment by vinoddanekar** [comment]
Got it.
1. I guess, due to https redirection its saying "successfully added" but not adding it to directory. Will remove redirection.
2. On production its working fine now. It adds to peppol directory too. We dont have redirection on production.

Thank you so much for your support & guidance.

Closing the issue.
