### ISSUE TITLE
Missing endpoint reference on detail view

### ISSUE THREAD

**Issue by seltzlab** [phax/phoss-smp#162]
The detail view for an endpoint is showing the field endpoint reference with a `none` value even if the value is filled (indeed correctly seen in the edit view of the same endpoint).

**Comment by phax** [comment]
Sorry, but I can't reproduce this with version 5.3.2. Can you eventually post your SMP URL here?

**Comment by anto-acube** [comment]
hello :) http://peppol-smp-sandbox.acubeapi.com

**Comment by phax** [comment]
It seems to have been a caching issue.
