### ISSUE TITLE
Cannot delete from SML

### ISSUE THREAD

**Issue by ri4a** [phax/phoss-smp#164]
#163 works! However, such service groups can now not be deleted in the UI since the delete in the SML fails.

Deletion should check the SML result to see why it could not be deleted. If it wasn't there in the first place, the delete in the SMP should succeed.

**Comment by phax** [comment]
Yes, that is clear. The workaround to that scenario is, to
1. go to the SMP Settings
2. Disable SML usage
3. Delete the Service Groups
4. go again to the SMP Settings
5. Re-enable SML usage

Of coure a checkbox would be nice, which indicates "delete also in SML"

**Comment by ri4a** [comment]
Good workaround, closing.
