### ISSUE TITLE
Request for Db check API

### ISSUE THREAD

**Issue by arditkazazi** [phax/phoss-smp#171]
Hello, 
is it possible to have a rest api that checks if the db connection is working properly? 

Regards
Ardit

**Comment by phax** [comment]
I decided to do it in the regular status API.
The name of the item in the status list is called `smp.sql.db.connection-possible` and has a boolean value.
In case of "not possible" it takes approx. 4 seconds with a local MySQL to get the timeout.

As this may be tedious in other scenarios, when "/smp-status" is used for health checking, this long running operation can be disabled in the configuration file `smp-server.properties` by setting the property `smp.status.sql.enabled` to `false`.

This will be part of the 5.4.0 release.
