### ISSUE TITLE
Request for a new configuration setting to log authentication failures

### ISSUE THREAD

**Issue by dineshk-ibm** [phax/phoss-smp#174]
Hi,

As discussed, I kindly request your to enable a configuration setting to log authentication failures for security auditing purposes.

Please let me know if you need more information.

Thanks,
Dinesh.

**Comment by phax** [comment]
@dineshk-ibm  I crosschecked, and this should already been done today. So no action needed. It can be found as action `login` with success state "failure" in the audit.

I tried it with my SMP instance and this is what I get:
![grafik](https://user-images.githubusercontent.com/196219/135686392-b889dd89-6e6e-4be8-9af0-06fbedaac344.png)

Sorry for the unnecessary work.
