### ISSUE TITLE
Peppol id inserted in SML but not in SMP

### ISSUE THREAD

**Issue by arditkazazi** [phax/phoss-smp#178]
It happened for some strange case that the SMP was able to insert the peppol id in the SML but it received an error after that. Every time it tried to recreate it received an error beacause the peppol id already existed in the SMP . I resolved the issue by inserting the peppol id (0211:IT02551570308) directly in the tables of db, deleting the service group from GUI and than recreating it.  Attached you can find the logs of smp in production.
Regards
[sata-peppol-smp.log](https://github.com/phax/phoss-smp/files/7545197/sata-peppol-smp.log)

**Comment by phax** [comment]
Hi Ardit,
Manually inserting something in the database is ALWAYS a bad idea.

In such cases, please do the following:
1. Goto the menu item "SMP Settings"
2. Disable the checkbox "SML enabled"
3. Perform the action you need - create or delete Service Group
4. Goto the menu item "SMP Settings"
5. Re-enable the checkbox "SML enabled"

If you need more assistance, please provide the exact error message.

**Comment by arditkazazi** [comment]
Hi Phil,
thanks for the tip.

Regards
Ardit

**Comment by phax** [comment]
You received an HTTP 400 from the SML.
Please see https://github.com/phax/phoss-smp/wiki/SML-notes for potential sources of this error.
Usually what I expect is, that the participant is already registered by a different SMP, but that is hard to test afterwards

**Comment by phax** [comment]
Closing this for now. I don't see any pending task....
