### ISSUE TITLE
Question About Participant ID forced lowercase

### ISSUE THREAD

**Issue by Legione85** [phax/phoss-smp#183]
Hi,

I'm using the phoss 5.2.0 and when I'm creating a new service group from the UI it's always created in lowercase.

Seeing some scheme ID (for the example the 0210 ) it seems that for the rules it requires uppercase letters.

There's a way in the configuration to not force the lowercase on the UI?

Maybe I'm missing something on the rules of the Peppol network

Any advice or reference will be appreciated.

Thanks

**Comment by phax** [comment]
Hi @Legione85,
Thanks for asking :)
That is a bit tricky, but it is correct for the usage in Peppol.
As you can read in the Peppol Policy for use of Idenfiers (https://docs.peppol.eu/edelivery/policies/PEPPOL-EDN-Policy-for-use-of-identifiers-4.0-2019-01-28.pdf), in Policy 2: "All Participant Identifier values have to be treated case insensitive even if the underlying scheme 126 requires a case sensitive value."

And that is why the SMP does this lowercasing - to handle the participants "case insensitive". But it only does it, if the SMP is configured in "peppol" mode and if the participant identifier scheme is "iso6523-actorid-upis".

hth

**Comment by Legione85** [comment]
thanks Philip, 

I think this reference should settle any controversy, until this policy is not modified of course

**Comment by phax** [comment]
This policy is one of the cornerstones of Peppol and I don't see why this should be changed, as this would be very disruptive.
Don't forget to update on v5.4.3 because of the Log4J issue....
