### ISSUE TITLE
Migration from 5.4.3 to 5.4.4 version (Docker XML backend) does not populate data from xml files

### ISSUE THREAD

**Issue by JonasZal** [phax/phoss-smp#185]
Hi,

Before the issue, with Log4J I was using 5.3.2 version with XML backend.
Direct Docker image update to 5.4.4 didn't work. SMP showed empty participants list and credentials didn't work.
So I decided to upgrade versions step by step, from 5.3.2 to 5.3.3 and so on.
I ended up with 5.4.3 version that was able to read XML data.

What I'm missing? Thank you in advance.

**Comment by herrlock** [comment]
We had this problem as well.
From 5.4.3 to 5.4.4 the working directory changed from /home/git to /usr/local/tomcat
Is your configuration in the correct folder?

**Comment by JonasZal** [comment]
Thank you @herrlock for the idea. But it wasn't enough for me. I changed webapp.datapath from relative to absolute and mounted data dir to the configured path. And it works now.

**Comment by phax** [comment]
Sorry for that. I was glad I found a way to reduce the image size by 25% but failed to set the home dir correctly. I will provide an updated to the 5.4.4 image to fix this issue. Sorry for the inconvenience caused.

**Comment by phax** [comment]
The new Docker images with the correct `WORKDIR` are now available. Sorry for the unconvenience caused.
