### ISSUE TITLE
Error creating new SMP Service Group

### ISSUE THREAD

**Issue by bdijk12** [phax/phoss-smp#187]
We have deployed a new release, but when we try to create a service group we get the below error:

Error creating the new SMP Service Group for participant 'iso6523-actorid-upis::0106:xxxxxxx'.
Technical details: SMPInternalErrorException - Error creating ServiceGroup 'iso6523-actorid-upis::0106:xxxxxxx'
Caused by: SQLException - Caught exception while perfoming something in a level 1 transaction [2]
Caused by: RegistrationHookException - Could not create business iso6523-actorid-upis::0106:xxxxxx in SML
Caused by: ClientTransportException - The server sent HTTP status code 404: null

It looks like it is running into an SQL issue, so I re-inited the database, to no avail.

Any thoughts how to debug this issue further?

**Comment by bdijk12** [comment]
Hi,

I did some checking:

Id 9944:62405292 is registered at the SMK

When creating a new service group I now get

Error creating the new SMP Service Group for participant 'iso6523-actorid-upis::9944:62405292'.
Technical details: SMPInternalErrorException - Error creating ServiceGroup 'iso6523-actorid-upis::9944:62405292'
Caused by: SQLException - Caught exception while perfoming something in a level 1 transaction [3]
Caused by: RegistrationHookException - Could not create business iso6523-actorid-upis::9944:62405292 in SML
Caused by: ClientTransportException - The server sent HTTP status code 400: Bad Request

But: when I try to create one for

iso6523-actorid-upis::0106:23082475

It works.

So where does it go wrong?



Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by bdijk12** [comment]
I deleted the SMP from the SMK, and tried to reregister.

Error registering SMP 'QUYNTESS-SMK' with physical address '94.228.219.40' and logical address 'http://smp-test.quyntess.com' to the SML 'https://acc.edelivery.tech.ec.europa.eu/edelivery-sml'.
Technical details: ClientTransportException - Der Server hat HTTP-Statuscode 400 gesendet: Bad Request

Now I’m really stuck.

Any ideas?

Bart-Jan

**Comment by bdijk12** [comment]
I'll be stumped. I redeleted the SMP and now it worked.

Successfully registered SMP 'QUYNTESS-SMK' with physical address '94.228.219.40' and logical address 'http://smp-test.quyntess.com' to the SML 'https://acc.edelivery.tech.ec.europa.eu/edelivery-sml'.

**Comment by bdijk12** [comment]
And now of course, my participants are not know and I cannot delete them

**Comment by bdijk12** [comment]
And found that check-dns state can help :-) Nice

**Comment by phax** [comment]
Okay, so you are digging yourself the way through :)
Alternatively you can always go to the "SMP Settings" and disable the SML there.
Than you can create/delete entries "just locally".
Btw. I can't reach your SMP from the outside.

**Comment by bdijk12** [comment]
Under which url?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by bjdijk** [comment]
I removed all paths from port 80 except /secure. Is that correct or  should I block more on oort  80?

**Comment by phax** [comment]
If the SMP is for Peppol it MUSt run the query API under Port 80. You can put /secure etc. under Port 443 if you like

**Comment by phax** [comment]
In the meantime I can access http://smp-test.quyntess.com/public from my machine - nice

**Comment by phax** [comment]
So I assume everything works now as expected?

**Comment by bjdijk** [comment]
Yes. Although the http errors are a bit strange. Seems to arise ifyou do
not wait long enough for the update to go through. Am I correct?

Op ma 10 jan. 2022 21:17 schreef Philip Helger ***@***.***>:

**Comment by phax** [comment]
These errors can have plenty of reasons. 
If you have a slow network, you may increase the `sml.connection.timeout.ms` and `sml.request.timeout.ms` values to increase the timeout.
The other HTTP errors from the SML usually have a semantic meaning as described in https://github.com/phax/phoss-smp/wiki/SML-notes
