### ISSUE TITLE
Change Owner of Service Group separately

### ISSUE THREAD

**Issue by sakasaka19** [phax/phoss-smp#195]
On GUI, I change the Owner of Service Group from A to B , and the same time All other Service Group owned by A  are changed to B automatically.

Is it the intended movement?

phoss-smp-backend-sql\src\main\java\com\helger\phoss\smp\backend\sql\mgr\SMPServiceGroupManagerJDBC.java

Best regards

**Comment by phax** [comment]
I don't think so. I fear this is an unintended side effect. I will look at it

**Comment by phax** [comment]
Will be fixed in 5.6.0 - thanks for pointing that out!

**Comment by phax** [comment]
Part of 5.6.0 release

**Comment by sakasaka19** [comment]
I am always helped by you.
Thank you always.
