### ISSUE TITLE
Call Rest API with Access Token

### ISSUE THREAD

**Issue by sakasaka19** [phax/phoss-smp#196]
I want to call Rest API with Access Token that I made on Phoss-SMP.
Can I call Rest API with Access Token ?

**Comment by phax** [comment]
@sakasaka19  Very good input - thanks.
Let me check what the implications are. In general I don't see an immediate problem.

You mean e.g. passing that via a custom HTTP header like
```
SMP-Token: <accessToken>
```
right?

**Comment by sakasaka19** [comment]
I'm sorry to reply late.
Yes. I want to passing that via a custom HTTP header.

I found the menu of user token management(Access Token) in GUI of SMP , So I thought that I can use access token in the place of HTTP Basic Auth(ID/Password Login).
but I don't understand how to use Access Token in SMP.

**Comment by phax** [comment]
Yes, the Access Token is foreseen in the security concept, but it can currently not be used to identify users via the API.
I like this request and will see, if I can squeeze it into 5.6.0 release, but I am not 100% sure I find the time to do so

**Comment by sakasaka19** [comment]
OK.
I'm looking forward to it.
Thank you always.

**Comment by phax** [comment]
Part of SMP 6.0.7 release

**Comment by smahieu87** [comment]
It seems to be working now (version 6.0.7). As an 'Authorization' header you just add "Bearer ${token}" and it should work.
