### ISSUE TITLE
V17 Migration error in PostgreSQL

### ISSUE THREAD

**Issue by tmhide** [phax/phoss-smp#201]
The following query will result in a syntax error.
https://github.com/phax/phoss-smp/blob/master/phoss-smp-backend-sql/src/main/resources/db/migrate-postgresql/V17__SecUserTypeChange-PostgreSQL.sql

Please modify it as follows.
```
ALTER TABLE smp_secuser ALTER COLUMN loginname TYPE varchar(200);
ALTER TABLE smp_secuser ALTER COLUMN loginname SET NOT NULL;
ALTER TABLE smp_secuser ALTER COLUMN email TYPE varchar(200);
```

**Comment by phax** [comment]
Damnit. Thanks

**Comment by phax** [comment]
Part of 5.6.1 release

**Comment by phax** [comment]
@tmhide  Thanks again - 5.6.1 is available - also on Docker Hub
