### ISSUE TITLE
Error in deleting ServiceGroup that is not registered in SML from SMP

### ISSUE THREAD

**Issue by sakasaka19** [phax/phoss-smp#205]
I can't delete the Service Group that is not registered in SML from SMP .
Error message "Caused by: ClientTransportException - The server sent HTTP status code 404: Not Found".
Looks like SMP is trying to delete again a ServiceGroup that I already deleted from SML in the "Check DNS state of participants" page .

Best regards

**Comment by phax** [comment]
Hi @sakasaka19  that can happen when a participant was created without the SML being enabled.

I recommend you first check the participant on https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant - it the participant is not registered to the network or if the participant belongs to a different SMP, then you can follow this procedure:
1. Login to the secure area
2. Goto Administration | SMP Settings and press "Edit"
3. Uncheck the "SML Connection enabled" checkbox and press "Save"
4. Goto to the "Service Group" page, and delete the Service Group in question
5. Goto Administration | SMP Settings and press "Edit"
6. Check the "SML Connection enabled" checkbox again and press "Save"

That's it.
hth

**Comment by sakasaka19** [comment]
I could delete ServiceGroup.
Thank you for your response.
