### ISSUE TITLE
Suggest to change the type of smp_service_metadata_red.redirectionurl

### ISSUE THREAD

**Issue by tmhide** [phax/phoss-smp#206]
https://github.com/phax/phoss-smp/blob/e1466bca2210155ac1d4fc9cdea8739db54a1c6f/phoss-smp-backend-sql/src/main/resources/db/migrate-postgresql/V1__InitDatabase-5.2-PostgreSQL.sql#L93

The type of smp_service_metadata_red.redirectionurl is varchar(256).
This is short because redirectionurl contains documentIdentifier(varchar(500)) and businessIdentifier(varchar(50)).
I suggest that the type of smp_service_metadata_red.redirectionurl be text.

```
ALTER TABLE smp_service_metadata_red ALTER COLUMN redirectionurl TYPE text;
ALTER TABLE smp_service_metadata_red ALTER COLUMN redirectionurl SET NOT NULL;
```

**Comment by phax** [comment]
Thanks, that makes sense - let me see, if I can squeeze that into the next update

**Comment by phax** [comment]
Thanks :) Part of the 5.7.0 release
