### ISSUE TITLE
ServiceGroups in "Migrated" cannot be selectable in the Migrate to another SMP

### ISSUE THREAD

**Issue by sakasaka19** [phax/phoss-smp#209]
When trying to Migrate in the Migrate to another SMP menu in the GUI
ServiceGroup with a history in "Migrated" cannot be selected because it is not included in the drop-down list.
Incidentally, it is possible to register the corresponding ServiceGroup to Migrate to another SMP using the REST API.

Assuming this kind of movement
1. Regist ServiceGroup to this SMP
2. Migrate to another SMP
3. Finalize
4. Regist ServiceGroup again by Migrating to this SMP
5. I can't migrate to another SMP again.

ServiceGroups in "In Progress" cannot be selectable, but ServiceGroups in "Migrated" should be allowed.

**Comment by phax** [comment]
This is a very artificial case, but I will remove the limits on the UI for this

**Comment by phax** [comment]
Part of the 5.7.0 release
