### ISSUE TITLE
Cannot use Env variables in smp-server.properties

### ISSUE THREAD

**Issue by francescodiperna** [phax/phoss-smp#216]
Good morning, I need to use env variable for the db password in smp-server.properties but this doesn't work. Is there another way to do this?
The SMP application run on AKS Azure.

Kind regards

**Comment by phax** [comment]
Hi Francesco,
currently it is not possible to specify a single configuration property from a different source.
It is the plan for the next major release, to update the contained "configuration subsystem" to be more flexible.

In the meantime I don't see an easy way to do this, without creating the final configuration file on the fly. Something like this:
* You have a file "smp-server.properties.template" that uses `$DBPW` as the placeholder
* You use "awk" or "sed" to replace `$DBPW` with the content of the env var
* Store the output as "smp-server.properties"
* Start Tomcat with the system property `smp.server.properties.path` pointing to the absolute path of "smp-server.properties" as described in https://github.com/phax/phoss-smp/wiki/Configuration#smp-serverproperties

The next major version will use https://github.com/phax/ph-commons/wiki/ph-config as the configuration engine which allows to use Sytem Properties or Env Vars for each properties individually.

hth, Philip

**Comment by francescodiperna** [comment]
Thanks Philip for the fast response.

Kind regards
