### ISSUE TITLE
Peppol directory keystore error - Failed to locate key store path 'keystore/keystore.jks'. Technical details: Failed to open key store 'keystore/keystore.jks'

### ISSUE THREAD

**Issue by francescodiperna** [phax/phoss-smp#223]
Good morning, I configured everything in dev environment without error, but I have the following error in the production env.
When I click "Peppol directory keystore" in the menu "Certificate information" I got the error:
`Failed to locate key store path 'keystore/keystore.jks'. Technical details: Failed to open key store 'keystore/keystore.jks'`

I'm using the 5.7 version.
Thanks

I attach the configuration files, does something is wrong? Thanks in advanc
[application.properties.txt](https://github.com/phax/phoss-directory/files/9037316/application.properties.txt)
[smp-server.properties.txt](https://github.com/phax/phoss-directory/files/9037317/smp-server.properties.txt)
[webapp.properties.txt](https://github.com/phax/phoss-directory/files/9037318/webapp.properties.txt)
e

**Comment by phax** [comment]
Hi, I moved this to the SMP project.

The problem is, that all of your configuration files have leading spaces in the lines. That's why the values are not used.

So please change
````ini
    smp.keystore.type         = PKCS12
    smp.keystore.path         = /config/keystore/oxalis-keystore-produzione.p12
```
in all occurrances to 

````ini
smp.keystore.type         = PKCS12
smp.keystore.path         = /config/keystore/oxalis-keystore-produzione.p12
```

**Comment by francescodiperna** [comment]
Thanks Philip, there aren't leading spaces. Is just a mistake on the sample file I have attached.

**Comment by phax** [comment]
Okay, what installation form are you using
* Regular deployment in Tomcat
* Docker
* Something else?

Where are the configuration files located - it seems like they are not found. Are you using environment variables or system properties to reference them, or did you replace the default files?

**Comment by francescodiperna** [comment]
Docker. 
The env variabile CONFIG_FILE, SMP_SERVER_CONFIG and SMP_WEBAPP_CONFIG refer to the correct path.

```
CONFIG_FILE=/config/application-produzione.properties
SMP_SERVER_CONFIG=/config/smp-server-produzione.properties
SMP_WEBAPP_CONFIG=/config/webapp-produzione.properties
```
Everythink works well us you can check on this link but only the peppol directory certificate has the error.
https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0211%3AIT01446720680+&sml=digitprod&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform

**Comment by francescodiperna** [comment]
```
ls -lat /config/
total 40
drwxr-xr-x 1 root root 4096 Jul  4 11:52 .
-rw-r----- 1 root root  906 Jul  4 10:35 sml-info.xml
-rw-r----- 1 root root  436 Jul  4 09:21 smtpsettings.xml
-rw-r----- 1 root root  312 Jul  4 09:21 systemmigrations.xml
drwxr-x--- 2 root root 4096 Jul  4 09:21 security
drwxr-xr-x 1 root root 4096 Jul  4 09:20 ..
-rw-r--r-- 1 root root 1254 Jul  4 09:20 application-produzione.properties
-rw-r--r-- 1 root root 3211 Jul  4 09:20 smp-server-produzione.properties
drwxr-xr-x 1 root root 4096 Jul  1 15:29 keystore
-rw-r--r-- 1 root root 1736 Jul  1 15:29 webapp-produzione.properties
```

**Comment by phax** [comment]
Can you compare the screenshots in the page "Certificate information" between the tab "SMP Keystore" and "Peppol Directory Keystore"?
It seems like the application properties files seems not to be found....

**Comment by francescodiperna** [comment]
I think you are right, I have checked in the configuration files menu and I found this, but I don't know why
![Screenshot from 2022-07-04 12-28-53](https://user-images.githubusercontent.com/91900123/177136857-47b1169b-958a-459b-9559-92b9901d5d98.png)
.

**Comment by phax** [comment]
Ah okay. Yes I see - that is a problem I have identified after the 5.7.0 release.
There is a default configuration file present that is used by accident.
If you re-pull the image, the problem should be resolved, because then the default application.properties should be removed.

**Comment by francescodiperna** [comment]
Thanks Philip, I found the error. It was in my dockerfile, the variable CATALINA_OPTS pass as parameter a different property file path. Now I have the same path of the env variabile. 
Do I need to use both? If I remove the "-D" parameter in CATALINA_OPTS is used the paths of environment varabiles?

Bye

**Comment by francescodiperna** [comment]
I was using a docker file that compile the source code.
Bye

**Comment by phax** [comment]
Okay, then please check your Dockerfile against the latest changes:
https://github.com/phax/phoss-smp/commit/bf24f3e5b05d6132febf274933ada843a12ca115

**Comment by francescodiperna** [comment]
Fantastico! Grazie Philip, you are precious :-)

**Comment by francescodiperna** [comment]
Yes, everything is working.
Bye
