### ISSUE TITLE
Business card disappear after creation or update

### ISSUE THREAD

**Issue by InterzenConsulting** [phax/phoss-smp#224]
Good morning, I'm using the version 5.7.0.
When I create a new business card adding only the name and the country I have no error but if ha add other information like "additional information" or "geographic information" the business card disappear without error, as you can see in the screenshot.

Philip, can you help me?

By

Di Perna Francesco
![Screenshot from 2022-07-07 10-09-23](https://user-images.githubusercontent.com/91658072/177724452-a3753a1b-46a6-4c37-b489-853c8d12e82c.png)

**Comment by phax** [comment]
@InterzenConsulting please let me know what version of the SMP with what backend (XML, SQL - which DB, MongoDB) are you using?

**Comment by francescodiperna** [comment]
Hi Philip, is the version 5.7.0 SQL

**Comment by phax** [comment]
Ah, hey @[francescodiperna](https://github.com/francescodiperna) :)
With PostgreSQL right? Which PostgreSQL version is it (for testing)?

**Comment by phax** [comment]
I tried to reproduce it but failed.

Can you please try to check the log file for any anomailies?

Additionally, if you add the property `jdbc.debug.sql=true` to your `smp-server.properties` file you will get extended debug output on what's going on.

**Comment by francescodiperna** [comment]
Hi, you can close this ticket. I do not have the error now, and I do not know why.
Bye and thanks
