### ISSUE TITLE
Understand how to use SMP business level signature and minumum authentication level

### ISSUE THREAD

**Issue by duke-nuke** [phax/phoss-smp#228]
Hi 
i need to understand the the purpose of these two fields while defining the Endpoint , 
<smp:RequireBusinessLevelSignature>false</smp:RequireBusinessLevelSignature>
<smp:MinimumAuthenticationLevel>2</smp:MinimumAuthenticationLevel>

if you can describe and how can i make use of these two fields to increase the confidentiality and security between two parties.
Regards

Khurram

**Comment by phax** [comment]
Hi Khurram,
these fields are purely "self declarational" and have no explicit security enhancement.
If you are using Peppol, the `RequireBusinessLevelSignature` and the `MinimumAuthenticationLevel` are not evaluated.
In other projects, it depends on the caller / user of the response.

hth
