### ISSUE TITLE
Cannot update Business Card: "Error notifying the Peppol Directory to index"

### ISSUE THREAD

**Issue by MengXinAlex** [phax/phoss-smp#229]
Hi @phax ,

I faced an issue while updating the Business Cards. **I could register new service groups, endpoints and business cards**, but I cannot sync to PEPPOL Directory. 
![image](https://user-images.githubusercontent.com/46865258/199664419-d25bee8c-4cd6-4130-bb48-2d3bc8a59cdb.png)

This is my SMP setting:
![image](https://user-images.githubusercontent.com/46865258/199664976-44157998-17d1-4cda-8c7d-a069ad373fff.png)

I'm not sure if the endpoint has been successfully registered or not, but after the registration, I could find the records on [Peppol Practical Tool](https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant), but no record on [Peppol Directory](https://directory.peppol.eu/public),

This issue happened after I updated the certificate for both production(SML) and testing(SMK) environments, but the testing instance don't have any issues after that.

Regards,
Alex

**Comment by phax** [comment]
Hi @MengXinAlex,
The following possibilities come to my mind:
1. This SMP instance is configured with a Peppol Test (Pilot) certificate and you want to push to the production Directory (directory.peppol.eu). This will not work - please change the settings to use "https://test-directory.peppol.eu" instead.
2. You configured a TLS truststore for the PD client (properties `pdclient.truststore.*` - see https://github.com/phax/phoss-directory/#client-configuration-properties) that does not contain the proper certificates
3. You forget to properly configure the PD client keystore (properties `pdclient.keystore.*` - see also https://github.com/phax/phoss-directory/#client-configuration-properties )

What version of SMP are you running? Did you recently update to a newer version?

hth, Philip

**Comment by MengXinAlex** [comment]
Hi Philip,

Thanks for your reply. You are right, after I changed `truststore.*` to `pdclient .truststore.`* in `pdclient.properties`, The problem fixed. 

Thank you again for your help, I appreciate it.
