### ISSUE TITLE
PKI certificate says invalid password

### ISSUE THREAD

**Issue by vinoddanekar** [phax/phoss-smp#233]
Hi,

I got new PKI certificate for Production. When I update it to Keystore and click on reload keystore then it shows below error:
![image](https://user-images.githubusercontent.com/46052955/217827841-ab0f7388-0a5e-4a7c-bdf6-4f7aad09bfeb.png)

I do the same process that I did last year for staging.
Version: phoss SMP 5.4.5

The certificate shows all data properly in keytool https://keystore-explorer.org/index.html 

When I open same certificate in Keopatra - it shows error of object id.

Can you please help me understanding the problem?

**Comment by phax** [comment]
Hi @vinoddanekar, please consider updating the SMP version. Your version is very old (December 2021).

Most likely your configuration file has a trailing blank at the end of the password??
Did you set the keystore type (JKS or PKCS12) correctly?

hth Philip

**Comment by vinoddanekar** [comment]
Its PKCS12. There is no problem with config as its working with old certificate already. In new cert I just need to change alias and append root certificate. When I do that using https://github.com/phax/phoss-smp/wiki/Certificate-setup#peppol-pki-v3-starting-2018 It corrupts the certificate. I did not face this problem when I did same steps for Test certificates last year. All happened smooth.

Weird thing is that when I open imported certificate in Kleopatra then it opens properly. When I open Kse and edit alias and try to open it in Kleopatra then it save "Invalid Object" which looks similar to above error "data is not an objectid". 

Weirdest is that, if I edit alias with keytool - still I face the same problem.

Could it be a problem with JAVA versions? I have JRE 1.8, JDK 11.0 - I tried setting both environment variables one by one but no luck.

Software update - I will do soon.

**Comment by phax** [comment]
Honestly I think I cannot really help you from here.
My proposal would be you start fresh, with the certificates you received from OpenPeppol:
Then follow the procedure described on the above link you pasted.
* Make sure you ceate a keystore of type "pkcs12" and make sure you use the correct type in the configuration file (`smp.keystore.type`).
* Make sure the alias in the configuration file matches the alias from the keystore.
* Make sure you know the password to the keystore AND (potentially different) password to the key itself
* Make sure all values in the configuration files use the correct casing

hth

**Comment by vinoddanekar** [comment]
I guess, the problem is with new Kse version.
![image](https://user-images.githubusercontent.com/46052955/218128592-e93bf2de-5617-45dd-b911-2f1dc622ffe6.png)

By default the strong is selected. I just tried to change it to legacy then it worked in Kleopatra. Will check tomorrow morning whether it works for SMP software.

**Comment by vinoddanekar** [comment]
HI Philip,

My suspect was correct. It worked. It needs "legacy" encryption. Solved my problem :)

Hope it helps someone.

Thanks.

**Comment by phax** [comment]
Hi @vinoddanekar  Thanks for the information - very valuable!!!!

**Comment by phax** [comment]
Ah, this is a new setting in KSE v5.5.2 - I updated the Certificate setup guide accordingly

**Comment by vinoddanekar** [comment]
Great! Thanks.
