### ISSUE TITLE
Could not register servicegroup contents in the SMK

### ISSUE THREAD

**Issue by robrechtD** [phax/phoss-smp#246]
We use phoss smp version 5.4.5.
We use the rest api to register a new participant and endpoints. 
The registration is successful and both the service group and endpoints are created in the SMP. 
In the SMK however only the participant is registered and not the endpoints. 
The SML connection is enabled and set to the SMK.
This used to work until a couple weeks ago.
I cannot find any error in the SMP logs.
Any idea where I can start looking for the cause of the problem?

**Comment by phax** [comment]
Hi, that is totally okay.
The SMK is only informed about the participant identifiers, the endpoints are never synchronized to the SMK.
Please see e.g. https://peppol.helger.com/public/menuitem-docs-smp-sml-interplay for a detailed explanation about the interplay between SMP and SML.

If this is not what you meant, please try to just explain the problem you are facing and the result you would expect.

hth, Philip

**Comment by robrechtD** [comment]
Hi Philip

When looking up the entry during document transmission, we receive the following error:
_Combination of receiver (iso6523-actorid-upis::9925:be0563470723) and document type identifier (busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1) is not supported._

I can also not see the document types when looking up the participant manually: https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0208%3A0563470723&sml=digittest&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform

In the SMP however, I do find the document types:
![image](https://github.com/phax/phoss-smp/assets/15961871/68c5ed83-6cfb-47be-9ac2-7654eab68501)

I'd expect the document types to show up like they do in production (other smp): https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0208%3A0563470723&sml=digitprod&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform

**Comment by robrechtD** [comment]
I also contacted the SMK with my issue, turns out our HTTP => HTTPS redirect broke on the test environment, causing issues in the SMK.

Restoring this functionality has fixed the problem.

**Comment by phax** [comment]
@robrechtD  thanks for the information.
The usage of HTTP is a requirement of the Peppol SMP specification. Please see https://docs.peppol.eu/edelivery/smp/PEPPOL-EDN-Service-Metadata-Publishing-1.2.0-2021-02-24.pdf chapter 5.1.
