### ISSUE TITLE
Problem Create New Service Group

### ISSUE THREAD

**Issue by DioMeo** [phax/phoss-smp#264]
Hello, I was creating a new service group in my SMP.
After entering all informations, when I try to save, I have this problem:

![immagine](https://github.com/phax/phoss-smp/assets/146419702/b1470ee7-d29f-4123-824a-eb23c7cdeb28)

Thanks

**Comment by DioMeo** [comment]
I found this issue opened 2 years ago: https://github.com/phax/phoss-smp/issues/154, so
I created my truststore folder and copied the files:
- "complete-truststore.jks" 
- "directory-truststore.jks"
- "sml-truststore.jks"
- created "2018" folder and copied "pilot-truststore.jks"

![immagine](https://github.com/phax/phoss-smp/assets/146419702/9e8cb234-7c79-4594-b782-37a98027f197)

as the guide says: https://github.com/phax/peppol-commons/tree/master/peppol-commons/src/main/resources/truststore

I configured my "application.properties" like this:

![immagine](https://github.com/phax/phoss-smp/assets/146419702/692685b9-a9a6-40f0-af32-b8ca3f6f8b10)

I restarted tomcat and apache services but the problem is not solved.

I don't have any problem with the certificate like the Issue 154:

![immagine](https://github.com/phax/phoss-smp/assets/146419702/844da89e-9872-4a0e-b567-261ee4af8798)

Any ideas?
Thanks.

**Comment by DioMeo** [comment]
Hi Philip, I solved the problem.
I disabled all the configurations in SMP Settings, tried to import the partecipants and it worked successfully, and I reactivated the configurations.
Thanks for support

**Comment by phax** [comment]
@DioMeo  super :) Yes a common work around is always to dynamically disable the SML, do something and re-enable the SML.
