### ISSUE TITLE
Problem With Endpoint Tree Loading Error

### ISSUE THREAD

**Issue by DioMeo** [phax/phoss-smp#266]
Hello Philip, I wanted to report to your attention a problem with the loading of "Enpoints -> Endpoint Tree", that it goes in Error 502

![image](https://github.com/phax/peppol-reporting/assets/146419702/1a38eea0-b4e5-4a15-ae60-dd6f6c103941)

We gave 8 CPU to our server, but it is useless because tomcat eats all the CPU:

![image](https://github.com/phax/peppol-reporting/assets/146419702/10e9c28e-1911-44ea-8da7-9dd3a0ef546f)

Any ideas?

Thanks.

**Comment by phax** [comment]
This is a known issue, because there is no paging on that list, and it can be become very huge. Please work with the endpoint list instead - sorry.

**Comment by DioMeo** [comment]
Hello Philip, thank you for reply and we'll work with endpoint list.
