### ISSUE TITLE
Peppol Directory integration - Rest API - custom deactivation 

### ISSUE THREAD

**Issue by dextreza** [phax/phoss-smp#269]
It would be beneficial to extend the current API that creates/updates the BusinessCards in order to let in every single request to decide if that particular BusinessCard will be notified to the Peppol directory or not regardless the SMP configuration is configured as TRUE. 
API path: PUT /businesscard/{ServiceGroupId}

**Comment by dextreza** [comment]
Forgot to mention about other APIs that could be also triggering the notifications to the PD. i guess that every PUT or DELETE API over ServiceGroupIds, ServiceRegistrations or BusinessCards could be affected as well.

**Comment by phax** [comment]
Changing the "Directory automatic update" flag with the REST API is a bad idea. This setting is global and will continue to work so. However, I will add an API that will allow you to "only push" the Business Card of a specific Participant to the configured Directory. So if you know, that the automatic update is disabled, you can manually trigger this.

**Comment by phax** [comment]
The new API will be part of the 7.1.5 release. It will be a `POST` with the URL pattern `/businesscard/{participantID}/push`.

See the REST API documentation for details: https://github.com/phax/phoss-smp/wiki/REST-API
