### ISSUE TITLE
Internal error in addServiceGroupToIndex from SMP server

### ISSUE THREAD

**Issue by katoduwee** [phax/phoss-smp#282]
Hi Philip,

We received a weird error from the SMP server based on your phoss-smp repository. You can find the stacktrace from our logs in annexe. The specific error we encountered was the following: `[2024-07-09T09:05:54,315] [SMP-SERVER] [ERROR] [http-nio-8080-exec-11] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::0106:01072024 -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$0(PDClient.java:62)`

Is this a common error? What is the PDClient? How do we fix this? 

[extract-2024-07-11T15_46_06.021Z.csv](https://github.com/user-attachments/files/16190781/extract-2024-07-11T15_46_06.021Z.csv)

**Comment by phax** [comment]
Hi @katoduwee,
In your log, you show adding a Business Card via REST API.
In this case, it seems like you had issues with reaching the Peppol Directory on a network level. Most likely the Directory was busy.... Just try again and you should be good.
`PDClient` is the "Peppol Directory Client" and is used to trigger the update of the BusinessCard inside the Directory solution (directory.peppol.eu and test-directory.peppol.eu)

**Comment by katoduwee** [comment]
Hi, 

Thank you for the quick response!
Is there a reason we ain't calling the peppol directory asynchronously since it doesn't affect the status of the createBusinesscard?

**Comment by phax** [comment]
@katoduwee No, there is no particular reason why this isn't called asynchronously.
Calling it synchronously is just easier :)
However, in this case there is no harm. The only consequence is, that the Business Card is not syneced to the Directory. With the next change of the ServiceInformation of that participant, the Business Card gets pushed again, or you can simply push the "sync all" button on the GUI.

**Comment by phax** [comment]
@katoduwee  is there anything else you need to know, or can this issue be closed?
