### ISSUE TITLE
Broken link in the REST API documentation

### ISSUE THREAD

**Issue by mikalammi** [phax/phoss-smp#293]
There is a broken link in the intro chapter, https://github.com/phax/phoss-smp/wiki/REST-API#rest-api-introduction which is meant to lead to the Peppol SMP specification, https://docs.peppol.eu/edelivery/smp/PEPPOL-EDN-Service-Metadata-Publishing-1.2.0-2021-02-24.pdf. I am getting an error message

> 404 Not Found
> Code: NoSuchKey
> Message: The specified key does not exist.
> Key: edelivery/smp/PEPPOL-EDN-Service-Metadata-Publishing-1.2.0-2021-02-24.pdf
> RequestId: 4A8EAY2Y006SBA76
> HostId: vh8NkI5WPO7otTVVfQDnYUqivBABlBWGbcLpsyRBNdbDDS4Ox5IZN5q6U3oY8WfpKMvchyQJqU8=
> An Error Occurred While Attempting to Retrieve a Custom Error Document
> Code: NoSuchKey
> Message: The specified key does not exist.
> Key: error.html

**Comment by phax** [comment]
Thanks, point taken. Latest version 1.3.0. I will link to the top-level directory instead.
