### ISSUE TITLE
Bulk change url or certificates with XML backend causes the entire service to hang

### ISSUE THREAD

**Issue by seciq** [phax/phoss-smp#297]
Hi,

After upgrading from 7.1.4 to 7.1.5 I've discovered that bulk change causes the entire service to freeze.

After I click "Save change" on "Bulk change URL" I'm not forwarded back to the overview page and no response is sent back from the server. In another browser if I try to do a lookup for a service group the request just hangs and never completes.

The issue was discovered in our test environment where we have approximately 2000 service groups however,
I was able to reproduce this locally with 5 service groups and two endpoints.

Can this be related to the locking mechanism used for XML backend and the new logic introduced in this commit: https://github.com/phax/phoss-smp/commit/2dac81d038734259d98b1191d587f723c21eccce ?

Environment information (local):
- Image: phelger/phoss-smp-xml:7.1.6
- Number of service groups: 5
- Number of endpoints: 2
- 4 CPU | 6 GB RAM

In the logs the following line keep popping up:
 
phoss-smp  | [2024-10-08T12:47:05,991] [SMP-SERVER] [ERROR] [RequestTrackerMonitor-1] Long running request. ID=11; millisecs=564502; Remote IP=172.20.0.1; URL=http://localhost:8080/secure/locale-en_US/menuitem-endpoints_change_url?phprga -- com.helger.commons.log.LogHelper.log(LogHelper.java:492)

**Comment by phax** [comment]
Thanks for the information. I will create a 7.1.7 release immediately.

**Comment by seciq** [comment]
Thanks a lot. I've tested with v7.1.7 and problem is now fixed.
