### ISSUE TITLE
Directory publication per participant

### ISSUE THREAD

**Issue by mirvnillith** [phax/phoss-smp#301]
It looks like you can only enable/disable Peppol directory publication globally, but it could be useful to have this at participant level. I.e. default to publish (or not) and then optionally override that per participant.

**Comment by phax** [comment]
Well, you can decide by yourself whom to publish by only selectively creating Business Cards.
Currently the Peppol Network does not mandate the publication of Business Cards, so you are not forced to create them.
As the Business Cards have no other goal than to be read by the Peppol Directory this seems to be the easiest way forward. What do you think?

**Comment by mirvnillith** [comment]
Ah, didn't realise that was the "trigger" for directory publication and thought it was only a nice-to-have option for adding even more information.
