### ISSUE TITLE
Impossible to use SMP with Oracle due to Oracle's table name limitations

### ISSUE THREAD

**Issue by JonasZal** [phax/phoss-smp#62]
Current DDL (https://github.com/phax/peppol-smp-server/blob/master/peppol-smp-server-sql/database_backups/smp_20161012.sql) is not aligned with Oracle's table naming rules. Table name cannot exceed 30 char.

Table smp_service_metadata_redirection cannot be created due to limitations because it's name is 32 char length.

**Comment by phax** [comment]
Part of 5.6.0 release
