### ISSUE TITLE
Metadata migration support

### ISSUE THREAD

**Issue by wiecia** [phax/phoss-smp#78]
Hi Philip, we are implementing SMP SML communications using your phoss software. One of the requirements is ability to migrate participant metadata from one SMP to another as stated in SML documentation. Is it supported by phoss, as I cannot find any code related to this functionality. In not - what are other options to accomplish that? Thanks

**Comment by wiecia** [comment]
Hi, thanks for your reply.
I'm not sure however if this is what I mean. I was thinking about the process of migrating user identifier on one SMP to another SMP which is hosted by different provider. In SML documentation this process is described to be initiated by destination SMP, aquiring migratoin key and then doing actual migration (with all metadata I think)

**Comment by phax** [comment]
@wiecia you are absolutely right.
I forgot about this. Yes, there is a service at the SML to move a participant from one SMP to another but that is rarely ever used. phoss SMP does not support this atm.
Do you need this?

**Comment by wiecia** [comment]
@phax yes :) we are implementing national EDI service based on PEPPOL and including several service providers (we're one of it). The requirement is to be able to have such procedure available and what's more - this has to be done in an automatic manner (not including human operator). Also all different actions on SMP also are triggered automatically (by calling REST endpoints if available).

BTW, if we registered 1000 users/service groups (which is the our requirement) and each ot them has 4 - 6 documents defined the UI listing this data takes ages to pull it from DB and display, but this should be reported in separate ticket.

**Comment by phax** [comment]
See e.g. https://github.com/phax/peppol-smp-server/issues/62 on the data model

**Comment by phax** [comment]
Ah okay. Because I'm writing with Andrzej and it seems like it's about the same issue....

**Comment by phax** [comment]
This is finally in place for v5.4.0
